"""
This file contains a method to produce all the outputs you would need to run a case using Mehdi's framework
for a PT-specific case. Requires a surface mesh (ending in 'cl_mapped.vtp') with a 'taylor_len' array, generated by map_info.py.

Call this script using:
make_mesh.py proj_dir proj_name min_el max_el multi_inlets ref

Where 
-proj_dir is the directory where the surface mesh is stored,
-proj_name is the name you want all of your files to start with,
-min_el and max_el are your min and max edge lengths that you want,
-multi_inlets indicates whether there are more than one inlet (options are 'Multi' and 'single'),
-ref indicates if you want a refinement patch, defined as a mask in map_info.py, and is a float 
indicating the level of refinement (eg. 0.8) you want

Note: if you run this script a second time with the same mesh, it will remesh the surface for you before going to the vmtkmeshgenerator!!
"""

import numpy as np
import pyvista as pv
from geometry_tools.meshing import Mesher
from vmtk import vmtkscripts
import geometry_tools.vmtk_wrapper as vmtk
import geometry_tools.common as cc
from geometry_tools.make_submission_file import SubmissionTemplate
from scipy.interpolate import interp1d
from pathlib import Path
import sys

def create_size_array(surf, min_el=0.2, max_el=0.7, ref='False'):
    min_tay=min(surf.point_data['taylor_len'])
    max_tay=max(surf.point_data['taylor_len'])
    print('Sizing array...')
    #print(np.isnan(sum(surf.point_data['CSA'])),np.isnan(sum(surf.point_data['perimeter'])), np.isnan(sum(surf.point_data['flowrate'])), np.isnan(sum(surf.point_data['taylor_len'])))
    interp = interp1d([min_tay, max_tay], [min_el, max_el], 
        kind='linear',
        bounds_error=False,
        fill_value=(min_el, max_el),
        )
    surf.point_data['Size'] = interp(surf.point_data['taylor_len'])
    print('Smoothing array...')
    surf, neighbour_pts = cc.smooth_mesh_data_local_alt(surf, array='Size', iterations = 20)
    if ref !='False':
        if float(ref) < 1:
            surf.point_data['Size'][surf.point_data['ref']==1]=float(ref)*surf.point_data['Size'][surf.point_data['ref']==1]
            surf, _ = cc.smooth_mesh_data_local_alt(surf, array='Size', neighbour_pt_ids = neighbour_pts, iterations = 10)
        else:
            surf.point_data['Size'][surf.point_data['ref']==0]=float(ref)*surf.point_data['Size'][surf.point_data['ref']==0]
            surf, _ = cc.smooth_mesh_data_local_alt(surf, array='Size', neighbour_pt_ids = neighbour_pts, iterations = 10)
    return surf

def make_mesh(proj_dir, proj_name, min_el, max_el, multi_inlets, ref):
    if not proj_dir.exists():
        proj_dir.mkdir()
    main_dir = proj_dir.parent
    mapped_file = sorted(main_dir.glob('*_mappedsys.vtp'))[0]
    backup_file = proj_dir / (mapped_file.name.split('.')[0] + '_backup.vtp')
    mesh_out_dir = proj_dir / 'mesh' 
    data_out_dir = proj_dir / 'data' 
    vtufile = mesh_out_dir / (proj_name + '.vtu')
    meshfile = data_out_dir / (proj_name + '.h5')
    infofile = data_out_dir / (proj_name + '.info')
    fcoeffsfile = data_out_dir / ('FC_VENOUS')
    xmlgzfile = data_out_dir / (proj_name + '.xml.gz')
    for f in [mesh_out_dir, data_out_dir]:
        if not f.exists():
            f.mkdir(parents=True, exist_ok=True)

    surf=pv.read(mapped_file)
    m = Mesher(
            surf,
            include_aneurysms=False
            )

    #make refinement patch if it doesn't already exist
    if (ref != 'False') and ('ref' not in m.surf.point_data):
        ref_select = cc.RefinementSelection(m.surf, name='ref')
        ref_select.select()
        ref_select.define_surface()
        m.surf = ref_select.surf
        m.surf.save(mapped_file)
	
    if 'Size' in m.surf.point_data:
        #check if the min and max edge lengths have changed in the command (rounded to two decimal places)
        if (round(max(m.surf.point_data['Size']), 2)!=round(float(max_el), 2)) or (round(min(m.surf.point_data['Size']), 2)!=round(float(min_el), 2)):
            m.surf = create_size_array(m.surf, min_el=float(min_el), max_el=float(max_el), ref=ref)
            m.surf.clean()
            m.surf.save(mapped_file) #add size array to file
        surf = vmtk.surface_remeshing(m.surf, element_size_mode='edgelengtharray', edgearray='Size', iterations=10)
        projection = vmtkscripts.vmtkSurfaceProjection()
        projection.Surface = surf
        projection.ReferenceSurface = m.surf
        projection.Execute()
        m.surf = pv.wrap(projection.Surface)
        skip_remeshing=1
    else:
        #save mapped surface file that isn't yet remeshed
        m.surf.save(backup_file)
        m.surf = create_size_array(m.surf, min_el=float(min_el), max_el=float(max_el), ref=ref)
        m.surf.clean()
        skip_remeshing=0
    m.surf.save(mapped_file) #add size array to file
    m.set_inlets_outlets()
    #send surface to vmtk
    if not vtufile.exists():
        m.generate_volume_mesh(SkipRemeshing = skip_remeshing)
        m.mesh.save(vtufile)
    else:
        m.mesh = pv.read(vtufile)
    #print(m.surf)
    m.centerlines, _ = vmtk.network_extractor(m.surf)
    m.centerlines = vmtk.centerline_geometry(m.centerlines)

    m.update_inlets_outlets()
    if not meshfile.exists():
        m.generate_h5_file(meshfile)
    if multi_inlets == 'single':
        m.outlet_flow_divisions = {} #not sure why generate flow rates not working. Prob something not done
    m.generate_info_file(infofile, fcoeffsfile, multi_inlets, inlet_vel=False, inlet_flowrates=[5.299944445, 0.92981481, 0.92981481, 0.92981481], waveform='FC_VENOUS')  
    if not xmlgzfile.exists():
        m.generate_xml_gz_file(xmlgzfile)

    # Create submission file
    min_EL = np.min(m.surf.point_data['Size'])
    max_vel = 3*np.max(m.surf.point_data['mean_velocity']) #factor of safety 3
    tstep_per_cycle = 5*int(60*np.round((max_vel*915/min_EL)/60)) #round to nearest multiple of 60 with a factor of safety here of 5
    s = SubmissionTemplate(proj_name, timesteps_per_cycle=tstep_per_cycle, save_frequency=1)
    s.save_script(proj_dir)


if __name__ == "__main__":
    use_parser = True
    if len(sys.argv) == 1:
        try:
            import config
            proj_dir = Path(config.mm_proj_dir)
            print(f"Using the settings outlined in the config.py file. Project directory: {proj_dir}")
            proj_name = config.mm_proj_name
            min_el = config.mm_min_el
            max_el = config.mm_max_el
            multi_inlets = config.mm_multi_inlet
            ref = config.mm_ref
            use_parser = False
        except Exception as e:
            print(f"Exception encountered: {e}\nDefaulting to passed parameters")
    if use_parser:
        proj_dir = Path(sys.argv[1]) 
        proj_name=sys.argv[2]
        min_el=sys.argv[3]
        max_el=sys.argv[4]
        multi_inlets = sys.argv[5]
        if len(sys.argv)>6:
            ref=sys.argv[6]
        else: 
            ref='False'
    make_mesh(proj_dir=proj_dir, proj_name=proj_name, min_el=min_el, max_el=max_el, multi_inlets=multi_inlets, ref=ref)
